name: tailscale

on:
  workflow_dispatch:

jobs:
  tailscale:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: tailscale/github-action@main
        with:
          oauth-secret: ${{ secrets.OAUTH_SECRET }}
          version: 1.44.0
          tags: tag:ci

      - run: tailscale netcheck
